### ISSUE TITLE
Fizzbuzz CLI Tool Exercise #1

### ISSUE THREAD

**Issue by nmcapule** [TrishtanPamatmat/Trishtan_Hexaware_Onboarding#1]
**Deliverables**

- [ ] Create a simple CLI tool that could calculate the [classic FizzBuzz exercise](https://en.wikipedia.org/wiki/Fizz_buzz). See Requirements section for details
- [ ] Add unit tests that can be invoked with `plz test ..`
- [ ] Reply into this issue your estimate (preferably in hours or days) to complete
- [ ] Close this issue once finished
- [ ] Add instructions how to compile / run your code using please.build

**Requirements**

Please create an invokeable cli tool using Go and please.build that could do the FizzBuzz problem.

- The tool will be invoked with a single required parameter. For example: `./fizzbuzz 10`
- Once executed, the code will iterate from 1 up to the given input parameter.
  - If i % 3 == 0, print "Fizz"
  - If i % 5 == 0, print "Buzz"
  - If i % 15 == 0, print "Fizz Buzz"
  - else print i
- Sample invocations:

```sh
$ ./fizzbuzz 3
  1
  2
  Fizz
$ ./fizzbuzz 5
  1
  2
  Fizz
  4
  Buzz
$ ./fizzbuzz 1
  1
```

> Tip: If you can't find the binary compiled by plz, `plz run //src:main -- 1` is the same as invoking with `./fizzbuzz 1`

I'll wait for updates every weekday 4PM. Good luck!

**Comment by TrishtanPamatmat** [comment]
Hi There @nmcapule 
Hopefully I finished this tom afternoon before you check it.
Thanks man!

**Comment by TrishtanPamatmat** [comment]
Closing this issue, Thanks!
Will be focusing on protractor.
